### ISSUE TITLE
Discord Link Invalid

### ISSUE THREAD

**Issue by lawrencefoley** [sourcehold/Sourcehold#19]
The Discord link on the [README](https://github.com/sourcehold/Sourcehold/blob/master/README.md) is invalid:
`https://discordapp.com/invite/736X9H`

Also, I just want to say, I'm excited to see this project. Really love Stronghold Crusader and I hope to be able to contribute.

**Comment by metalvoidzz** [comment]
Thanks, I added the correct link.
