### ISSUE TITLE
Imported targets on MacOS

### ISSUE THREAD

**Issue by skrax** [sourcehold/Sourcehold#37]
As you know, I have started cleaning up CMakeLists.txt and while doing so added imported targets like this:
```cmake
find_package(OpenAL REQUIRED)
add_library(OpenAL::OpenAL UNKNOWN IMPORTED)
set_target_properties(OpenAL::OpenAL PROPERTIES
  IMPORTED_LOCATION ${OPENAL_LIBRARY}
  INTERFACE_INCLUDE_DIRECTORIES ${OPENAL_INCLUDE_DIR})
```
As it turns out, on MacOS this will not fly, since it fails to link frameworks correctly.
As a result, I have found this solution:

```cmake
find_package(OpenAL REQUIRED)
if(APPLE)
  add_library(OpenAL::OpenAL INTERFACE IMPORTED)
  set_target_properties(OpenAL::OpenAL PROPERTIES
    APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${OPENAL_LIBRARY}
    INTERFACE_INCLUDE_DIRECTORIES ${OPENAL_INCLUDE_DIR})
else()
  add_library(OpenAL::OpenAL UNKNOWN IMPORTED)
  set_target_properties(OpenAL::OpenAL PROPERTIES
    IMPORTED_LOCATION ${OPENAL_LIBRARY}
    INTERFACE_INCLUDE_DIRECTORIES ${OPENAL_INCLUDE_DIR})
 endif()
```
MacOS should build fine now.

**Comment by gynt** [comment]
Great find! Is your example an example, or is it code that should be added still?

**Comment by apodrugin** [comment]
This issue was fixed in https://github.com/sourcehold/Sourcehold/pull/36

**Comment by skrax** [comment]
Ah, just saw it. Didn‘t have time to review your changes later that day.
I‘m on the road with my Macbook, so I experienced the issue myself

**Comment by gynt** [comment]
Your activity on this project really makes me happy!
